# remote_theme: just-the-docs/just-the-docs
# title: Res Virtualis
# color_scheme: light
# search_enabled: false
# plugins:
#   - jekyll-remote-theme




# remote_theme: "mmistakes/minimal-mistakes"
# title: Res Virtualis
# plugins:
#   - jekyll-remote-theme
#   - jekyll-include-cache

theme: jekyll-theme-cayman
title: ResVirtualis
show_github: false
